Add support for Nightwatch v3
nightwatchjs-community/nightwatch-typescript-boilerplate pull request #6
Opened 2023-07-31 12:59 UTC by garg3133

2023-08-01 08:26 UTC, vaibhavsingh97 requested changes

2023-08-01 08:26 UTC, vaibhavsingh97 commented on test/iFrame.ts
> +    browser.frame(iFrame.elements.iframe.selector);
```suggestion
    browser.frame('@iframe');
```

2023-08-01 08:33 UTC, garg3133 commented on nightwatch/tsconfig.json
> +  },
This is to show that the tsconfig present in the `nightwatch` folder should be intact and not changes should be made to it unless absolutely necessary.

2023-08-01 08:34 UTC, garg3133 commented on test/fileUpload.ts
> +      .strictClick(fileUpload.elements.submitButton)
Just to show another way of passing the element. Probably should do it on an internal command and also add a comment.

2023-08-01 08:34 UTC, garg3133 commented on test/iFrame.ts
> +    browser.frame(iFrame.elements.iframe.selector);
^ won't work. Dependent on https://github.com/nightwatchjs/nightwatch/pull/3819

2023-08-01 08:37 UTC, garg3133 commented on nightwatch/pages/Dropdown.ts
> +const _: PageObjectModel = dropdown;
Just to show another way of writing page objects, as `satisfies` is only available from TypeScript 4.9. Probably should also add a FAQ section in README and list this question: "We're using TypeScript < 4.9 which does not have a `satisfies` operator, how should we define the page objects?"

2023-08-01 08:37 UTC, garg3133 commented on .github/workflows/build.yml
> -        node-version: [14.x, 15.x, 16.x]
I think we should keep it as long as the main Nightwatch repo is supporting 14.x

2023-08-01 09:33 UTC, vaibhavsingh97 commented on nightwatch/pages/Dropdown.ts
> +const _: PageObjectModel = dropdown;
> should also add a FAQ section in README and list this question: "We're using TypeScript < 4.9 which does not have a satisfies operator, how should we define the page objects?"

Yes, a FAQ question sounds good to me.

2023-08-01 09:34 UTC, vaibhavsingh97 commented on nightwatch/pages/Dropdown.ts
> +const _: PageObjectModel = dropdown;
Why are we defining the `PageObjectModel` separately when we can assign it directly while defining the page object?

2023-08-01 09:38 UTC, vaibhavsingh97 commented on nightwatch/tsconfig.json
> +  },
yup, this makes sense

2023-08-01 09:41 UTC, vaibhavsingh97 commented on test/fileUpload.ts
> +      .strictClick(fileUpload.elements.submitButton)
Yes, we can add a comment showing possible ways of doing it.

```typescript
   fileUpload
      .navigate()
      .uploadFile('@fileUploadInput', filePath)
      .click('@submitButton')
      // we can also specify selector with @<selector-name>
      //.strictClick('@submitbutton')
      .strictClick(fileUpload.elements.submitButton)
```

2023-08-22 16:33 UTC, garg3133 commented on nightwatch/pages/Dropdown.ts
> +const _: PageObjectModel = dropdown;
Explained in the comment.

2023-08-22 16:35 UTC, garg3133 commented on test/fileUpload.ts
> +      .strictClick(fileUpload.elements.submitButton)
Done

2023-08-22 16:52 UTC, garg3133 commented
@beatfactor @gravityvi Can you please review this as well?

2023-08-22 16:55 UTC, garg3133 commented
Tests are only failing because of some config issues with BrowserStack, there are working fine locally.

2024-03-04 07:32 UTC, merged